#if we not specify make command it's will executed from top to bottom
#template Ex:
# target: prerequisites
#	commands

#first
#make or make build
build:
	gcc main.c -o main.o

#second
#make execute
execute:
	./main.o

clean:
	rm -rf *.o